### ISSUE TITLE
Exception in db raised with wrong arguments 

### ISSUE THREAD

**Issue by sveneberth** [viur-framework/server#186]
In the order method of our db.Query class we try to raise a BadArgumentError in the else case. But the used variable _fieldName_ is unknown in this scope.

https://github.com/viur-framework/server/blob/d068994d93e3d60b287e1877719ef93013ef76db/db.py#L547

### Solution 
To change the line to
```python
raise BadArgumentError("Dont know what to do with %s" % type(reqOrder))
```
Would be my intuitively suggestion. But _fieldName_ is never used.

### better Solution 
So we could reduce the whole for block
https://github.com/viur-framework/server/blob/d068994d93e3d60b287e1877719ef93013ef76db/db.py#L542-L547

to

```python
if not isinstance(reqOrder, basestring) and not isinstance(reqOrder, tuple):
	raise BadArgumentError("Dont know what to do with %s" % type(reqOrder))
```

 Another problem is that there is currently only a instance check for str. But anywhere the value is casted to unicode, therefore I changed it to basestring.

Would this be a good solution or have anyone a smarter one?

### Stacktrace

```shell
ERROR    2019-09-06 14:02:02,944 __init__.py:535] local variable 'fieldName' referenced before assignment
Traceback (most recent call last):
  File "/.../appengine/server/__init__.py", line 465, in processRequest
    self.findAndCall( path, *args, **kwargs )
  File "/.../appengine/server/__init__.py", line 657, in findAndCall
    self.response.out.write( caller( *self.args, **self.kwargs ) )
  File "/.../appengine/server/cache.py", line 118, in wrapF
    return( f( self, *args, **kwargs ) )
  File "/.../appengine/modules/myModule.py", line 299, in list
    query = self.listFilter( self.viewSkel().all().mergeExternalFilter( kwargs ) )
  File "/.../appengine/server/db.py", line 388, in mergeExternalFilter
    bone.buildDBSort( key, skel, self, filters )
  File "/.../appengine/server/bones/stringBone.py", line 313, in buildDBSort
    dbFilter.order( inEqFilter, order )
  File "/.../appengine/server/db.py", line 547, in order
    raise BadArgumentError("Dont know what to do with %s" % type(fieldName),)
UnboundLocalError: local variable 'fieldName' referenced before assignment

```

**Comment by phorward** [comment]
make it so. Otherwise, you can make a `logging.error` and continue, so the server won't crash.
